<a href="https://colab.research.google.com/github/venser21/Gen_AI/blob/main/NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

class NeuralNetwork:
    def __init__(self, layer_sizes):
        self.layer_sizes = layer_sizes
        self.num_layers = len(layer_sizes)
        self.weights = [np.random.randn(layer_sizes[i], layer_sizes[i-1]) for i in range(1, self.num_layers)]
        self.biases = [np.zeros((layer_sizes[i], 1)) for i in range(1, self.num_layers)]

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def forward_propagation(self, X):
        a = X
        activations = [a]
        zs = []

        for i in range(self.num_layers - 1):
            z = np.dot(self.weights[i], a) + self.biases[i]
            a = self.sigmoid(z)
            activations.append(a)
            zs.append(z)

        return activations, zs

    def backward_propagation(self, X, y, activations, zs):
        m = X.shape[1]
        gradients = []

        delta = activations[-1] - y
        dW = np.dot(delta, activations[-2].T) / m
        db = np.sum(delta, axis=1, keepdims=True) / m
        gradients.append((dW, db))

        for i in range(self.num_layers - 3, -1, -1):
            delta = np.dot(self.weights[i+1].T, delta) * (activations[i+1] * (1 - activations[i+1]))
            print(delta)
            dW = np.dot(delta, activations[i].T) / m
            db = np.sum(delta, axis=1, keepdims=True) / m
            gradients.append((dW, db))

        return gradients[::-1]

    def update_parameters(self, gradients, learning_rate):
        for i in range(len(gradients)):
            self.weights[i] -= learning_rate * gradients[i][0]
            self.biases[i] -= learning_rate * gradients[i][1]

    def train(self, X, y, num_iterations, learning_rate):
        for i in range(num_iterations):
            activations, zs = self.forward_propagation(X)
            gradients = self.backward_propagation(X, y, activations, zs)
            self.update_parameters(gradients, learning_rate)

        return activations[-1]

# Ejemplo de uso:
# Crear una red neuronal con 3 capas ocultas (5 neuronas en cada capa oculta)
layer_sizes = [2, 5, 5, 5, 1]
nn = NeuralNetwork(layer_sizes)

# Datos de entrenamiento
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]).T
y = np.array([[0, 1, 1, 0]])

# Entrenar la red neuronal
num_iterations = 10000
learning_rate = 0.1
output = nn.train(X, y, num_iterations, learning_rate)

# Imprimir el resultado
print("Resultado de la red neuronal después del entrenamiento:")
print(output)


Se han truncado las últimas 5000 líneas del flujo de salida.
 [-1.53090962e-03  3.64338446e-03  3.53419297e-03 -4.26105379e-03]
 [-2.36571637e-03  3.47424946e-03  3.61881928e-04 -2.07297708e-03]
 [ 1.80860577e-03 -3.81923871e-03 -3.42115849e-03  4.20113367e-03]]
[[ 9.32484703e-05 -4.80412064e-05 -2.70800314e-05  1.35252907e-04]
 [-1.78758878e-03  2.31279392e-03  2.35801222e-03 -3.70720084e-03]
 [ 1.23857963e-03 -1.15521257e-03 -1.18914519e-03  1.93622837e-03]
 [ 2.18613928e-03 -2.29923415e-03 -3.30617112e-03  4.38277566e-03]
 [ 6.32786164e-04 -9.30974232e-04 -9.74825232e-04  9.91535854e-04]]
[[ 0.00206771 -0.00293747 -0.00369203  0.00446452]
 [-0.00085397  0.00117642  0.00149307 -0.00158738]
 [ 0.00255852 -0.00463155 -0.00347453  0.00511231]
 [-0.00073927  0.00250682  0.00042837 -0.00182795]
 [ 0.00110738 -0.00195966 -0.00242328  0.00319066]]
[[ 2.80459969e-03 -9.90032097e-05 -3.36421137e-03  1.61283136e-03]
 [-3.71951830e-03  1.30268193e-03  1.45853627e-03 -2.60822467e-05]
 [-1.530458

In [4]:
np.sum([[1,2]],axis=1)

array([3])